apps/report/urls.py
from django.urls import path

from . import views

app_name = 'report'

urlpatterns = [
    path('v1/report/transaction/', views.TransactionReportView.as_view(), name='transaction'),
    path('admin/report/transaction/', views.TransactionReportAdminView.as_view(), name='transaction_view'),

    path('v1/report/voucher/', views.VoucherReportView.as_view(), name='voucher'),
    path('admin/report/voucher/', views.VoucherReportAdminView.as_view(), name='voucher_view'),

    path('v1/report/clean-test-data/', views.CleanTestUserView.as_view(), name='clean_test_data'),
    path('admin/report/clean-test-data/', views.CleanTestUserAdminView.as_view(), name='clean_test_data_view'),

    path('v1/report/users-sessions/', views.UserSessionView.as_view(), name='user_sessions'),
    path('admin/report/users-sessions/', views.UserSessionsAdminView.as_view(), name='user_sessions_view'),

    path('v1/report/dlp/', views.DLPView.as_view(), name='DLP'),
    path('admin/report/dlp/', views.DLPAdminView.as_view(), name='DLP_view'),
]

apps/user/urls.py
from rest_framework.routers import DefaultRouter

from django.urls import path, re_path

from user import views


app_name = 'user'


router = DefaultRouter()
router.register(r'', views.UserViewSet, base_name='user')


urlpatterns = [
    path('upload/', views.UserUploadView.as_view(), name='user_upload'),
    path('deactivate/', views.UserListDeactivate.as_view(), name='user_list_deactivate'),
    re_path(r'invite/(?P<token>[a-z,A-Z,0-9]{2,}-[a-z,A-Z,0-9]{2,}-[a-f,0-9]{2,})/$',
            views.UserInviteView.as_view(), name='signup_invite'),  # accept invite `User`
    path('password-reset/', views.UserPasswordResetRequestView.as_view(), name='password_reset'),  # request reset password
    re_path(r'password-reset/(?P<token>[a-z,A-Z,0-9]{2,}-[a-z,A-Z,0-9]{2,}-[a-f,0-9]{2,})/$',
            views.UserPasswordResetConfirmView.as_view(), name='password_reset_confirm'),  # change password confirm
]

urlpatterns += router.urls

apps/report/views.py
from decimal import Decimal

from rest_framework import generics
from rest_framework.views import APIView
from rest_framework.authentication import SessionAuthentication
from rest_framework.response import Response
from rest_framework.permissions import IsAuthenticated

from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import user_passes_test
from django.contrib.sessions.models import Session
from django.db.models import Count
from django.views.generic import TemplateView
from django.utils.decorators import method_decorator
from django.utils.timezone import now

from flexvoucher.models import InvoiceScan, PointsLoads, VoucherHistory, Voucher, Transaction
from flexvoucher.serializers import VoucherSerializer
from .authentications import CsrfExemptSessionAuthentication
from .filters import DateFilter, VoucherFilter, TransactionFilter
from .serializer import VoucherHistorySerializer, TransactionSerializer


class BaseReportAdminView(TemplateView):
    site_url = "/"

    @method_decorator(user_passes_test(
        lambda u: u.is_staff,
        login_url='admin:login'
    ))
    def dispatch(self, request, *args, **kwargs):
        return super(BaseReportAdminView, self).dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super(BaseReportAdminView, self).get_context_data(**kwargs)
        context['title'] = 'Transaction Report'
        context['user'] = self.request.user
        context['site_url'] = self.site_url
        context['has_permission'] = True
        return context


class BaseReportView(generics.ListAPIView):
    authentication_classes = (SessionAuthentication, )
    permission_classes = (IsAuthenticated, )  # TODO: check permissions


class TransactionReportView(BaseReportView):
    """
    Transaction for any given user activity on any given period
    """
    serializer_class = TransactionSerializer
    queryset = Transaction.objects.all()
    filter_backends = (TransactionFilter, )

    def get_queryset(self):
        query = super(TransactionReportView, self).get_queryset()
        user = self.request.user
        if not user.is_superuser and not user.is_admin and not user.is_accountant:
            query = query.filter(account__owner_id=self.request.user.pk)
        return query

    def list(self, request, *args, **kwargs):
        queryset = self.filter_queryset(self.get_queryset())

        serializer = self.get_serializer(queryset, many=True)
        data = serializer.data
        points_debit_sum = sum([Decimal(_['amount']) for _ in data
                                if _['transaction_type']['points_or_money'] == 'points' and
                                _['transaction_type']['credit_or_debit'] == 'debit'])
        points_credit_sum = sum([Decimal(_['amount']) for _ in data
                                if _['transaction_type']['points_or_money'] == 'points' and
                                 _['transaction_type']['credit_or_debit'] == 'credit'])
        money_debit_sum = sum([Decimal(_['amount']) for _ in data
                               if _['transaction_type']['points_or_money'] == 'money' and
                               _['transaction_type']['credit_or_debit'] == 'debit'])
        money_credit_sum = sum([Decimal(_['amount']) for _ in data
                                if _['transaction_type']['points_or_money'] == 'money' and
                                _['transaction_type']['credit_or_debit'] == 'credit'])
        resp = {
            'data': data,
            'sum': {
                'points_debit': points_debit_sum,
                'points_credit': points_credit_sum,
                'money_debit': money_debit_sum,
                'money_credit': money_credit_sum,
            }
        }
        return Response(resp)


class TransactionReportAdminView(TemplateView):
    template_name = "report/transaction_report.html"


class VoucherReportAdminView(TemplateView):
    template_name = "report/voucher_report.html"


class VoucherReportView(BaseReportView):
    """
    Vouchers for any given user activity on any given period
    """
    serializer_class = VoucherSerializer
    queryset = Voucher.objects.all()
    filter_backends = (VoucherFilter, )

    def get_queryset(self):
        query = super(VoucherReportView, self).get_queryset()
        user = self.request.user
        if not user.is_superuser and not user.is_admin and not user.is_accountant:
            query = query.filter(account__owner_id=self.request.user.pk)
        return query

    def list(self, request, *args, **kwargs):
        queryset = self.filter_queryset(self.get_queryset())

        serializer = self.get_serializer(queryset, many=True)
        data = serializer.data
        points_amount_sum = sum([_['points_amount'] for _ in data])
        money_amount_sum = sum([Decimal(_['money_amount']) for _ in data])
        resp = {
            'data': data,
            'sum': {
                'points_amount': points_amount_sum,
                'money_amount': money_amount_sum,
            }
        }
        return Response(resp)


class CleanTestUserView(APIView):
    authentication_classes = (CsrfExemptSessionAuthentication, )
    permission_classes = (IsAuthenticated, )  # TODO: check permissions

    def _get_users(self):
        query = get_user_model().objects.filter(account__is_test=True).annotate(Count('account__voucher'),
                                                                                Count('account__pointsloads'))
        data = list()
        for index, obj in enumerate(query, 1):
            row = dict(id=obj.pk,
                       index=index,
                       role='test',
                       username=obj.username,
                       vouchers=obj.account__voucher__count,
                       pointsloads=obj.account__pointsloads__count)
            data.append(row)
        return data

    def _clean_data(self):
        users_id = self.request.data['selectsUsersId']
        [_.delete() for _ in InvoiceScan.objects.filter(invoice_data__voucher__account__owner_id__in=users_id)]
        Voucher.objects.filter(account__owner_id__in=users_id).delete()
        PointsLoads.objects.filter(account__owner_id__in=users_id).delete()

    def get(self, request, *args, **kwargs):
        # request.query_params.get('action')
        data = self._get_users()
        return Response(data)

    def post(self, request, *args, **kwargs):
        # request.query_params.get('action')
        self._clean_data()
        data = self._get_users()
        return Response(data)


class CleanTestUserAdminView(TemplateView):
    template_name = "report/clean_test_user_data.html"


class UserSessionView(APIView):
    authentication_classes = (CsrfExemptSessionAuthentication, )
    permission_classes = (IsAuthenticated, )  # TODO: check permissions

    def _get_sessions(self):
        all_sessions = Session.objects.filter(expire_date__gte=now())
        session_key = self.request.session.session_key
        data = list()
        for index, session in enumerate(all_sessions, 1):
            session_data = session.get_decoded()
            row = dict(id=session.pk,
                       index=index,
                       expire_date=session.expire_date,
                       user_pk=session_data.get('_auth_user_id'),
                       current=session.pk == session_key)
            data.append(row)
        user_query = get_user_model().objects.filter(pk__in=set([_['user_pk'] for _ in data])).values('pk', 'username')
        lookup_dict = {str(_['pk']): _['username'] for _ in user_query}
        list(map(lambda x: x.__setitem__('username', lookup_dict.get(x['user_pk'])), data))
        return data

    def _clean_sessions(self):
        sessions_id = self.request.data['selectsSessionsId']
        Session.objects.filter(pk__in=sessions_id).delete()

    def get(self, request, *args, **kwargs):
        # request.query_params.get('action')
        data = self._get_sessions()
        return Response(data)

    def post(self, request, *args, **kwargs):
        # request.query_params.get('action')
        self._clean_sessions()
        data = self._get_sessions()
        return Response(data)


class UserSessionsAdminView(TemplateView):
    template_name = "report/user_sessions.html"


class DLPAdminView(TemplateView):
    template_name = "report/dlp.html"


class DLPView(BaseReportView):
    """ Dienstleistungpauschale Report
    """
    serializer_class = VoucherHistorySerializer
    queryset = VoucherHistory.objects.filter(voucher_status_id=10)  # paid
    filter_backends = (DateFilter, )

    def list(self, request, *args, **kwargs):
        queryset = self.filter_queryset(self.get_queryset())

        serializer = self.get_serializer(queryset, many=True)
        data = serializer.data
        points_amount_sum = sum([_['voucher']['points_amount'] for _ in data])
        money_amount_sum = sum([Decimal(_['voucher']['money_amount']) for _ in data])
        commission_sum = sum([_['voucher']['commission'] for _ in data])
        trans_sum = sum([_['voucher']['trans'] for _ in data])
        resp = {
            'data': data,
            'sum': {
                'points_amount': points_amount_sum,
                'money_amount': money_amount_sum,
                'commission': commission_sum,
                'trans': trans_sum,
            }
        }
        return Response(resp)

apps/report/templates/report/base_report.html
{% extends "admin/base_site.html" %}
{#{% extends "admin/index.html" %}#}
{% load i18n  %}
{% load static  %}

{% block extrastyle %}
    {{ block.super }}
    <link rel="stylesheet" type="text/css" href="{% static "admin/css/dashboard.css" %}" />
{% endblock %}

{% block coltype %}colM{% endblock %}

{% block breadcrumbs %}
<div class="breadcrumbs">
  <a href="{% url 'admin:index' %}">{% trans 'Home' %}</a> &rsaquo;
  <a href="{% url 'report:transaction' %}">{% trans 'Report Transactions' %}</a>
</div>
{% endblock %}

{% block content %}
<div id="content-main"></div>
{% endblock %}

{% block  extrajs%}
    <script src="{% static 'report/js/vendors/numeral.min.js' %}"></script>
    <script src="{%  static 'report/js/vendors/moment-with-locales.js' %}"></script>
    <script src="{% static 'report/js/vendors/babel.min.js' %}"></script>
    <script src="{% static 'report/js/vendors/react.development.js' %}" crossorigin></script>
    <script src="{% static 'report/js/vendors/react-dom.development.js' %}" crossorigin></script>
{#    <script src="https://unpkg.com/react@16/umd/react.production.min.js" crossorigin></script>#}
{#    <script src="https://unpkg.com/react-dom@16/umd/react-dom.production.min.js" crossorigin></script>#}
    <script src="{% static 'report/js/vendors/antd-with-locales.js' %}"></script>
    <script src="{% static 'report/js/vendors/axios.min.js' %}"></script>
    {% block custom_script %}{% endblock %}
{% endblock %}

{% block sidebar %}{% endblock %}

apps/report/templates/report/clean_test_user_data.html
{% extends "report/base_report.html" %}
{% load i18n  %}
{% load static  %}

{% block breadcrumbs %}
<div class="breadcrumbs">
  <a href="{% url 'admin:index' %}">{% trans 'Home' %}</a> &rsaquo; {% trans 'Clean test users data' %}
</div>
{% endblock %}

{% block custom_script %}
    <script src="{% static "report/js/clean-test-data.js" %}" type="text/babel"></script>
{% endblock %}

apps/report/templates/report/dlp.html
{% extends "report/base_report.html" %}
{% load i18n  %}
{% load static  %}

{% block breadcrumbs %}
<div class="breadcrumbs">
  <a href="{% url 'admin:index' %}">{% trans 'Home' %}</a> &rsaquo; {% trans 'Report DLP' %}
</div>
{% endblock %}

{% block custom_script %}
    <script src="{% static "report/js/dlp.js" %}" type="text/babel"></script>
{% endblock %}

apps/report/templates/report/transaction_report.html
{% extends "report/base_report.html" %}
{% load i18n  %}
{% load static  %}

{% block breadcrumbs %}
<div class="breadcrumbs">
  <a href="{% url 'admin:index' %}">{% trans 'Home' %}</a> &rsaquo; {% trans 'Report Transactions' %}
</div>
{% endblock %}

{% block custom_script %}
    <script src="{% static "report/js/transaction-report.js" %}" type="text/babel"></script>
{% endblock %}

apps/report/templates/report/user_sessions.html
{% extends "report/base_report.html" %}
{% load i18n  %}
{% load static  %}

{% block breadcrumbs %}
<div class="breadcrumbs">
  <a href="{% url 'admin:index' %}">{% trans 'Home' %}</a> &rsaquo; {% trans 'Staff users sessions' %}
</div>
{% endblock %}

{% block custom_script %}
    <script src="{% static "report/js/user-sessions.js" %}" type="text/babel"></script>
{% endblock %}

apps/report/templates/report/voucher_report.html
{% extends "report/base_report.html" %}
{% load i18n  %}
{% load static  %}

{% block breadcrumbs %}
<div class="breadcrumbs">
  <a href="{% url 'admin:index' %}">{% trans 'Home' %}</a> &rsaquo; {% trans 'Report Voucher' %}
</div>
{% endblock %}

{% block custom_script %}
    <script src="{% static "report/js/voucher-report.js" %}" type="text/babel"></script>
{% endblock %}